sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # 只监控 source 的 branch
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master # hexo 站点源文件所在的 branch
  local_dir: public 
  target_branch: public # 存放生成站点文件的 branch，使用 username.github.io 必须是 master